"""add product image url

Revision ID: a19bd634763a
Revises: 994962444015
Create Date: 2026-10-02 13:07:21.245801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a19bd634763a'
down_revision: Union[str, Sequence[str], None] = '994962444015'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.alter_column('products', 'quantity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('products', 'unit',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('products', 'location',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               nullable=False)
    op.alter_column('products', 'is_available',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_index(op.f('ix_products_farmer_id'), table_name='products')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_products_farmer_id'), 'products', ['farmer_id'], unique=False)
    op.alter_column('products', 'is_available',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('products', 'location',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('products', 'unit',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.alter_column('products', 'quantity',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_column('products', 'image_url')
    # ### end Alembic commands ###
